version: '3.4'
services:
  app:
    build: .
    container_name: Terracap-Legado
    ports:
      - 88:80
    volumes:
      - .:/var/www
    extra_hosts:
      - "api-interna-devdif:10.50.0.100"
      - "api-interna-devatual:10.50.0.27"
      - "api-interna-homol:10.50.61.13"
      - "gia-api-devdif:10.50.0.100"
      - "gia-api-devatual:10.50.0.27"
      - "gia-api-homol:10.50.61.13"
      - "gap-api-devdif:10.50.0.100"
      - "gap-api-devatual:10.50.0.27"
      - "gap-api-homol:10.50.61.13"
    command: "/usr/local/apache2/bin/apachectl -D FOREGROUND"
